version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.8
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler
      - ruby/bundle-install
      - rspec
